// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Entity;

#nullable disable

namespace ProductsAPI.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20240908103548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsActive = true,
                            Price = 1000m,
                            ProductName = "iPhone 14"
                        },
                        new
                        {
                            ProductId = 2,
                            IsActive = true,
                            Price = 2000m,
                            ProductName = "iPhone 15"
                        },
                        new
                        {
                            ProductId = 3,
                            IsActive = false,
                            Price = 3000m,
                            ProductName = "iPhone 16"
                        },
                        new
                        {
                            ProductId = 4,
                            IsActive = true,
                            Price = 4000m,
                            ProductName = "iPhone 17"
                        },
                        new
                        {
                            ProductId = 5,
                            IsActive = false,
                            Price = 5000m,
                            ProductName = "iPhone 18"
                        },
                        new
                        {
                            ProductId = 6,
                            IsActive = true,
                            Price = 6000m,
                            ProductName = "iPhone 19"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
